require: rubocop-rails

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/environments/*.rb
    - spec/**/*.rb

Metrics/MethodLength:
  Max: 20
  Exclude:
    - db/migrate/*.rb

Metrics/AbcSize:
  Exclude:
    - db/migrate/*.rb

Layout/LineLength:
  Exclude:
    - config/initializers/devise.rb

Rails/I18nLocaleTexts:
  Enabled: false

Rails/OutputSafety:
  Exclude:
    - config/initializers/field_with_errors.rb
