version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle:/bundle
    environment:
      RAILS_ENV: development
      DATABASE_URL: "postgres://postgres:postgres@db:5432/financial_transactions_app_development"
      WEB_CONCURRENCY: 1
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  bundle:
